/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.sakhalin2.caching_proxy;

import java.util.Map;

import org.junit.Test;

public class CachingProxyTest {

    @Test
    public void testSetupCachingProxy() {
        var parser = new CommandLineParser(new String[] { "--port", "35535", "--origin", "https://uibakery.io", "-r" });
        Map<CommandSwitch, String> cmdSwitchArgsMap = parser.parse();
        new CachingProxy("./app/logs").setup(cmdSwitchArgsMap);
    }
}
